import "~/styles/globals.css";

import { Inconsolata } from "next/font/google";

const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["200", "400"]
});

export const metadata = {
  title: "Can we go in the pool?",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inconsolata.variable}`}>{children}</body>
    </html>
  );
}
